// <auto-generated />
using System;
using HRMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HRMS.Data.Entities.Attendance", b =>
                {
                    b.Property<int>("Attendance_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attendance_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Attendance_Id"));

                    b.Property<string>("Attachment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attachment");

                    b.Property<DateTime>("Attendance_Date")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<string>("Attendance_Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("attendance_status");

                    b.Property<DateTime>("Check_In")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in");

                    b.Property<string>("Check_In_Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("check_in_mode");

                    b.Property<DateTime?>("Check_Out")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out");

                    b.Property<string>("Location_Detail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location_detail");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Work_Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("work_location");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("total_work_hours")
                        .HasColumnType("numeric(4,2)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Attendance_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("tbl_attendance");
                });

            modelBuilder.Entity("HRMS.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Log_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Log_Id"));

                    b.Property<string>("Action_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Module_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module_name");

                    b.Property<int>("Performed_User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("performed_user_id");

                    b.Property<int?>("Target_User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("target_user_id");

                    b.HasKey("Log_Id");

                    b.HasIndex("Performed_User_Id");

                    b.HasIndex("Target_User_Id");

                    b.ToTable("tbl_audit_log");
                });

            modelBuilder.Entity("HRMS.Data.Entities.Company", b =>
                {
                    b.Property<int>("Comp_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("comp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Comp_Id"));

                    b.Property<string>("Comp_Dummy1")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comp_dummy1");

                    b.Property<string>("Comp_Dummy2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comp_dummy2");

                    b.Property<string>("Comp_Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("comp_email");

                    b.Property<string>("Comp_Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comp_location");

                    b.Property<string>("Comp_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("comp_name");

                    b.Property<string>("Comp_Ph_No")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("comp_ph_no");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<TimeSpan>("Office_End_Time")
                        .HasColumnType("interval")
                        .HasColumnName("office_end_time");

                    b.Property<TimeSpan>("Office_Start_Time")
                        .HasColumnType("interval")
                        .HasColumnName("office_start_time");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Comp_Id");

                    b.ToTable("tbl_company");
                });

            modelBuilder.Entity("HRMS.Data.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dept_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dept_name");

                    b.Property<int?>("DeptHeadUserId")
                        .HasColumnType("integer")
                        .HasColumnName("dept_head_user_id");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DeptHeadUserId");

                    b.ToTable("tbl_department");
                });

            modelBuilder.Entity("HRMS.Data.Entities.LeaveBalance", b =>
                {
                    b.Property<int>("Balance_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("balance_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Balance_Id"));

                    b.Property<int>("Allocated_Days")
                        .HasColumnType("integer")
                        .HasColumnName("allocated_days");

                    b.Property<int?>("Carried_Forward_Days")
                        .HasColumnType("integer")
                        .HasColumnName("carried_forward_days");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Leave_Type_Id")
                        .HasColumnType("integer")
                        .HasColumnName("leave_type_id");

                    b.Property<int>("Remaining_Days")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_days");

                    b.Property<int>("Used_Days")
                        .HasColumnType("integer")
                        .HasColumnName("used_days");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Balance_Id");

                    b.HasIndex("Leave_Type_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("tbl_leave_balance");
                });

            modelBuilder.Entity("HRMS.Data.Entities.LeavePolicy", b =>
                {
                    b.Property<int>("Policy_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("policy_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Policy_Id"));

                    b.Property<int?>("Carry_Duration")
                        .HasColumnType("integer")
                        .HasColumnName("carry_duration");

                    b.Property<bool>("Carry_Forward")
                        .HasColumnType("boolean")
                        .HasColumnName("carry_forward");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Leave_Type_Id")
                        .HasColumnType("integer")
                        .HasColumnName("leave_type_id");

                    b.Property<int?>("Max_Carry_Day")
                        .HasColumnType("integer")
                        .HasColumnName("max_carry_day");

                    b.Property<DateTime>("Reset_Cycle")
                        .HasColumnType("date")
                        .HasColumnName("reset_cycle");

                    b.Property<int>("Total_Days")
                        .HasColumnType("integer")
                        .HasColumnName("total_days");

                    b.HasKey("Policy_Id");

                    b.HasIndex("Leave_Type_Id");

                    b.ToTable("tbl_leave_policy");
                });

            modelBuilder.Entity("HRMS.Data.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("Leave_Request_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("leave_request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Leave_Request_Id"));

                    b.Property<int>("Leave_Type_Id")
                        .HasColumnType("integer")
                        .HasColumnName("leave_type_id");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("approved_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("approved_by_user_id")
                        .HasColumnType("integer");

                    b.Property<string>("attachment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("remark")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("total_days")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Leave_Request_Id");

                    b.HasIndex("Leave_Type_Id");

                    b.HasIndex("User_Id");

                    b.HasIndex("approved_by_user_id");

                    b.ToTable("tbl_leave_request");
                });

            modelBuilder.Entity("HRMS.Data.Entities.LeaveType", b =>
                {
                    b.Property<int>("Leave_Type_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("leave_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Leave_Type_Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Leave_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("leave_name");

                    b.HasKey("Leave_Type_Id");

                    b.ToTable("tbl_leave_type");
                });

            modelBuilder.Entity("HRMS.Data.Entities.ProfileUpdateRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NewAddress")
                        .HasColumnType("text")
                        .HasColumnName("new_address");

                    b.Property<string>("NewPhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("new_ph_no");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("RequestId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_profile_update_request");
                });

            modelBuilder.Entity("HRMS.Data.Entities.PublicHoliday", b =>
                {
                    b.Property<int>("Holiday_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("holiday_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Holiday_Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Created_By_User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Holiday_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("holiday_name");

                    b.Property<string>("Holiday_Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("holiday_type");

                    b.Property<bool?>("Is_Recurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Holiday_Id");

                    b.HasIndex("Created_By_User_Id");

                    b.ToTable("tbl_public_holiday");
                });

            modelBuilder.Entity("HRMS.Data.Entities.Resignation", b =>
                {
                    b.Property<int>("Resignation_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("resignation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Resignation_Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Resignation_Date")
                        .HasColumnType("date")
                        .HasColumnName("resignation_date");

                    b.Property<string>("Resignation_Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("resignation_reason");

                    b.Property<int>("Resigned_By_User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("resigned_by_user_id");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Resignation_Id");

                    b.HasIndex("Resigned_By_User_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("tbl_resignation");
                });

            modelBuilder.Entity("HRMS.Data.Entities.Role", b =>
                {
                    b.Property<int>("Role_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Role_Id"));

                    b.Property<string>("Role_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role_name");

                    b.HasKey("Role_Id");

                    b.ToTable("tbl_role");
                });

            modelBuilder.Entity("HRMS.Data.Entities.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Dept_Id")
                        .HasColumnType("integer")
                        .HasColumnName("dept_id");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<DateTime>("Hired_Date")
                        .HasColumnType("date")
                        .HasColumnName("hired_date");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Married_Status")
                        .HasColumnType("integer")
                        .HasColumnName("married_status");

                    b.Property<string>("Nrc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nrc");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("qualification");

                    b.Property<string>("User_Dummy1")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_dummy1");

                    b.Property<string>("User_Dummy2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_dummy2");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name");

                    b.Property<string>("User_Ph_No")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_ph_no");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("User_Id");

                    b.HasIndex("Dept_Id");

                    b.HasIndex("Nrc")
                        .IsUnique();

                    b.HasIndex("User_Ph_No")
                        .IsUnique();

                    b.ToTable("tbl_user");
                });

            modelBuilder.Entity("HRMS.Data.Entities.UserAccount", b =>
                {
                    b.Property<int>("Account_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Account_Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<bool>("Is_First_Login")
                        .HasColumnType("boolean")
                        .HasColumnName("is_first_login");

                    b.Property<DateTime?>("Last_Login")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Password_Reset_Token")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_reset_token");

                    b.Property<int>("Role_Id")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("Token_Expiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expiry");

                    b.Property<int?>("User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Account_Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("tbl_user_account");
                });

            modelBuilder.Entity("HRMS.Data.Entities.Attendance", b =>
                {
                    b.HasOne("HRMS.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("HRMS.Data.Entities.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("Performed_User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS.Data.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("Target_User_Id");

                    b.Navigation("PerformedByUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("HRMS.Data.Entities.Department", b =>
                {
                    b.HasOne("HRMS.Data.Entities.User", "DeptHeadUser")
                        .WithMany()
                        .HasForeignKey("DeptHeadUserId");

                    b.Navigation("DeptHeadUser");
                });

            modelBuilder.Entity("HRMS.Data.Entities.LeaveBalance", b =>
                {
                    b.HasOne("HRMS.Data.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("Leave_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS.Data.Entities.LeavePolicy", b =>
                {
                    b.HasOne("HRMS.Data.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("Leave_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("HRMS.Data.Entities.LeaveRequest", b =>
                {
                    b.HasOne("HRMS.Data.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("Leave_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS.Data.Entities.User", "Approved_by")
                        .WithMany()
                        .HasForeignKey("approved_by_user_id");

                    b.Navigation("Approved_by");

                    b.Navigation("LeaveType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS.Data.Entities.ProfileUpdateRequest", b =>
                {
                    b.HasOne("HRMS.Data.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId");

                    b.HasOne("HRMS.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS.Data.Entities.PublicHoliday", b =>
                {
                    b.HasOne("HRMS.Data.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("Created_By_User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("HRMS.Data.Entities.Resignation", b =>
                {
                    b.HasOne("HRMS.Data.Entities.User", "HRApprover")
                        .WithMany()
                        .HasForeignKey("Resigned_By_User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HRApprover");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS.Data.Entities.User", b =>
                {
                    b.HasOne("HRMS.Data.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Dept_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRMS.Data.Entities.UserAccount", b =>
                {
                    b.HasOne("HRMS.Data.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
